version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shokooh
      POSTGRES_USER: shokoohuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - Backend

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: shokooh
      MINIO_ROOT_PASSWORD: shokoohpass
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    networks:
      - Backend

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    networks:
      - Backend

networks:
  Backend:
    driver: bridge
volumes:

  postgres_data:
    driver: local
  minio_data:
    driver: local